export const CATEGORIES = [
  "Engineering",
  "Design",
  "Research",
  "Finance",
  "News",
  "Personal",
  "Notes",
  "Health",
  "Legal",
  "Marketing",
  "Product",
  "Career",
  "Travel",
  "Food",
  "Real Estate",
  "Sports",
  "Politics",
  "Science",
  "History",
  "Philosophy",
  "Art",
  "Music",
  "Gaming",
  "Crypto",
  "AI",
  "Security",
  "Business",
  "Education",
  "Environment",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

/** Categories used for map/place pins (stored in the same `category` column). */
export const PLACE_CATEGORIES = [
  "Food",
  "Coffee",
  "Bar",
  "Entertainment",
  "Park",
  "Outdoors",
  "Shopping",
  "Hotel",
  "Museum",
  "Other",
] as const;

export type PlaceCategory = (typeof PLACE_CATEGORIES)[number];

export const CATEGORY_COLORS: Record<Category | PlaceCategory, string> = {
  Engineering: "#D4A0FF",
  Design: "#FFA0A0",
  Research: "#7EEDE4",
  Finance: "#8AD4E8",
  News: "#B8E6D0",
  Personal: "#FFEAA7",
  Notes: "#DFE6E9",
  Health: "#80FFD4",
  Legal: "#C4BFFF",
  Marketing: "#FFB0CB",
  Product: "#B8AFFE",
  Career: "#6EECC0",
  Travel: "#A0F0F0",
  Food: "#FFCABC",
  "Real Estate": "#A4D0FF",
  Sports: "#7EE8E4",
  Politics: "#FFB09A",
  Science: "#8DC8F8",
  History: "#E8C9A0",
  Philosophy: "#CDD5DB",
  Art: "#FF8DC7",
  Music: "#CBA4FF",
  Gaming: "#7EE8A0",
  Crypto: "#FFC04D",
  AI: "#7DD8E8",
  Security: "#FFA0A0",
  Business: "#B8A4FF",
  Education: "#93B8FF",
  Environment: "#6EE8B0",
  Coffee: "#D9B48F",
  Bar: "#F0A8E0",
  Entertainment: "#FFD080",
  Park: "#9AE89A",
  Outdoors: "#A8D8A0",
  Shopping: "#F8B8D8",
  Hotel: "#B0C8F8",
  Museum: "#E0C8F0",
  Other: "#C0CCD8",
};
